Repository meyer-lab/DrugResponseModel.jl, pull requests merged in 2020-11, with the labels that each got.

#361 Move over some cleanup
  src/allDrugs.jl
Labels: enhancement

#358 A bunch of reorganization
  Manifest.toml
  Project.toml
  src/DrugResponseModel.jl
  src/Hill.jl
  src/ODEmodel.jl
  src/allDrugs.jl
  test/testDrugAll.jl
  test/testODE.jl
Labels: enhancement

#364 Bliss clean
  Bliss.jmd
  Manifest.toml
  avgRepsAllDrugs.jmd
  combination.jmd
  makefile
  notebookPlots.jmd
  replicatesAtOnce.jmd
  separateDrugsAvg.jmd
  src/DrugResponseModel.jl
  src/combination.jl
  src/replicates.jl
  src/sensitivity.jl
  temporal_combination.jmd
  time_combin.jmd
Labels: enhancement

#369 Some cleanup
  src/ODEmodel.jl
  src/importData.jl
  src/plot.jl
  test/testHill.jl
  test/testODE.jl
Labels: formatting

#370 Sensitivity
  Project.toml
  src/DrugResponseModel.jl
  src/combination.jl
  src/sensitivity.jl
  test/runtests.jl
  test/testSensitivity.jl
Labels: current
